/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.dobackaofront.lanchonete.view;

import br.com.dobackaofront.lanchonete.model.Lanche;
import javax.swing.JOptionPane;

/**
 *
 * @author claudio.martins
 */
public class GUIMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMenu.class.getName());

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jInternalFrameCadastroLanche = new javax.swing.JInternalFrame();
        jLabelCadastroLancheNome = new javax.swing.JLabel();
        jTextFieldCadastroLancheNome = new javax.swing.JTextField();
        jLabelCadastroLanchePreco = new javax.swing.JLabel();
        jTextFieldCadastroLanchePreco = new javax.swing.JTextField();
        jButtonCadastroLancheSalvar = new javax.swing.JButton();
        jButtonCadastroLancheCancelar = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadastroLanche = new javax.swing.JMenuItem();
        jMenuEdicao = new javax.swing.JMenu();
        jMenuItemEdiçãoLanche = new javax.swing.JMenuItem();
        jMenuPesquisar = new javax.swing.JMenu();
        jMenuItemPesquisarLanche = new javax.swing.JMenuItem();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemVendaCarrinho = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanchonete Do Cláudio");

        jInternalFrameCadastroLanche.setTitle("Cadastro de Lanche");
        jInternalFrameCadastroLanche.setVisible(true);

        jLabelCadastroLancheNome.setText("Nome do Lanche");

        jLabelCadastroLanchePreco.setText("Preço:");

        jButtonCadastroLancheSalvar.setText("Salvar");
        jButtonCadastroLancheSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheSalvarActionPerformed(evt);
            }
        });

        jButtonCadastroLancheCancelar.setText("Cancelar");
        jButtonCadastroLancheCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroLancheCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameCadastroLancheLayout = new javax.swing.GroupLayout(jInternalFrameCadastroLanche.getContentPane());
        jInternalFrameCadastroLanche.getContentPane().setLayout(jInternalFrameCadastroLancheLayout);
        jInternalFrameCadastroLancheLayout.setHorizontalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addComponent(jButtonCadastroLancheSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastroLancheCancelar))
                    .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                        .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadastroLancheNome)
                            .addComponent(jLabelCadastroLanchePreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                                .addComponent(jTextFieldCadastroLanchePreco)
                                .addGap(67, 67, 67)))))
                .addGap(0, 88, Short.MAX_VALUE))
        );
        jInternalFrameCadastroLancheLayout.setVerticalGroup(
            jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameCadastroLancheLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLancheNome)
                    .addComponent(jTextFieldCadastroLancheNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroLanchePreco)
                    .addComponent(jTextFieldCadastroLanchePreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jInternalFrameCadastroLancheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastroLancheSalvar)
                    .addComponent(jButtonCadastroLancheCancelar))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jInternalFrameCadastroLanche, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroLanche)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrameCadastroLanche)
                .addGap(21, 21, 21))
        );

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadastroLanche.setText("Lanche");
        jMenuItemCadastroLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroLancheActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroLanche);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuEdicao.setText("Edição");

        jMenuItemEdiçãoLanche.setText("Lanche");
        jMenuEdicao.add(jMenuItemEdiçãoLanche);

        jMenuBarPrincipal.add(jMenuEdicao);

        jMenuPesquisar.setText("Pesquisar");

        jMenuItemPesquisarLanche.setText("Lanche");
        jMenuPesquisar.add(jMenuItemPesquisarLanche);

        jMenuBarPrincipal.add(jMenuPesquisar);

        jMenuVendas.setText("Vendas");

        jMenuItemVendaCarrinho.setText("Carrinho");
        jMenuVendas.add(jMenuItemVendaCarrinho);

        jMenuBarPrincipal.add(jMenuVendas);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroLancheActionPerformed
        jInternalFrameCadastroLanche.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroLancheActionPerformed

    private void jButtonCadastroLancheCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheCancelarActionPerformed
        // TODO add your handling code here:
        jTextFieldCadastroLancheNome.setText("");
        jTextFieldCadastroLanchePreco.setText("");
        jInternalFrameCadastroLanche.setVisible(false);
    }//GEN-LAST:event_jButtonCadastroLancheCancelarActionPerformed

    private void jButtonCadastroLancheSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroLancheSalvarActionPerformed
        // TODO add your handling code here:
                String nome = jTextFieldCadastroLancheNome.getText();
                
                if (nome.equals("")) {
                    JOptionPane.showMessageDialog(rootPane, "O campo Nome do Lanche está vazio!");
                    
                } else {
                    String preco = jTextFieldCadastroLanchePreco.getText();
                    
                    if (preco.equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "O campo Preço está vazio!");
                    } else {
                        try {
                            double precoConvertido = Double.parseDouble(preco);
                            Lanche lanche = new Lanche(nome, precoConvertido);
                            lanche.apresentarLanche();
                            
                            jTextFieldCadastroLancheNome.setText("");
                            jTextFieldCadastroLanchePreco.setText("");
                            
                            JOptionPane.showMessageDialog(rootPane,"O Lanche "+nome+" foi cadastrado com Sucesso!");
                            
                            jInternalFrameCadastroLanche.setVisible(false);
                        } catch(Exception e) {
                            JOptionPane.showMessageDialog(rootPane, "Preencha o preço do lanche apenas com numeros separados por ponto ao invés de virgula!");                 
                        }
                }     
                
        }
                
        
                
    }//GEN-LAST:event_jButtonCadastroLancheSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GUIMenu janelaPrincipal = new GUIMenu();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                janelaPrincipal.setVisible(true);
                janelaPrincipal.jInternalFrameCadastroLanche.setVisible(false);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroLancheCancelar;
    private javax.swing.JButton jButtonCadastroLancheSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrameCadastroLanche;
    private javax.swing.JLabel jLabelCadastroLancheNome;
    private javax.swing.JLabel jLabelCadastroLanchePreco;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEdicao;
    private javax.swing.JMenuItem jMenuItemCadastroLanche;
    private javax.swing.JMenuItem jMenuItemEdiçãoLanche;
    private javax.swing.JMenuItem jMenuItemPesquisarLanche;
    private javax.swing.JMenuItem jMenuItemVendaCarrinho;
    private javax.swing.JMenu jMenuPesquisar;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JTextField jTextFieldCadastroLancheNome;
    private javax.swing.JTextField jTextFieldCadastroLanchePreco;
    // End of variables declaration//GEN-END:variables
}
